# Generated by Django 4.0.3 on 2022-04-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomthought', '0002_alter_randomthought_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomthought',
            name='author_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='randomthought',
            name='author',
            field=models.CharField(max_length=64),
        ),
    ]
